.github/workflows/release.yml
.goreleaser.yml
Makefile
internal/version/version.go
testdata/memcached-molecule-operator/Makefile

- Update some version values to be v0.1.0 to prepare for the v0.1.0 release
- Prepare to cut a v0.1.0 release
**Checklist**
If the pull request includes user-facing changes, extra documentation is required:

prep for v0.1.0 release

---

Makefile
internal/version/version.go
testdata/memcached-molecule-operator/Makefile

- Updates the version used for the scaffolded Dockerfile FROM reference. This will need to be cherry picked to the release-v0.1 branch
- Forgot to do this for the v0.1.1 release and the v0.1.0 release was unsuccessful. Creating a v0.1.2 release to have our first fully usable release of this plugin.
**Checklist**
If the pull request includes user-facing changes, extra documentation is required:

release prep for v0.1.2

---

README.md

- Adds documentation on how to cut a release to the README
- Capture release process in documentation so it can be easily repeated by someone new to releasing in this repository

(docs): Add a release guide to the README

---

.github/PULL_REQUEST_TEMPLATE.md

Changelogs will be generated from git commits while documentation will still be contained in the main Operator SDK repository
Update the pull request checklist for the ansible-operator-plugins repository
Changelogs will be generated by `goreleaser` from git commits while documentation will still be contained in the main Operator SDK repository.
Closes #15

Remove pull request checklist

---

internal/ansible/controller/reconcile.go
internal/ansible/controller/status/utils_test.go

Given it is possible for a custom resource to be in error / failed state while a new reconcile process is ongoing, it is unnecessary to mark the status of previous Failure conditions to `False` while the reconcile loop is still running.
The failure condition will be removed when the custom resource is successfully deployed as it works today.
The failure conditions have timestamps and are accurate as at the time of reporting. Therefore, it would be unnecessary and misleading to set the failure condition status to `False` before the custom resource is successfully deployed.

Update conditions behavior after error

---

.goreleaser.yml
Makefile
internal/version/version.go
testdata/memcached-molecule-operator/Makefile

- Update versions to prepare for the v1.33.0 release
- Updates the goreleaser config to fix #36 
- Prepare for the v1.33.0 release

(release): prep for v1.33.0 release

---

internal/ansible/watches/testdata/env-vars.yaml
internal/ansible/watches/watches.go
internal/ansible/watches/watches_test.go

For any ${VAR} references in the watches yaml, this replaces those env vars with their values before the watches yaml is processed. If there is no ${VAR} defined, the "${VAR}" remains as-is in the watches yaml.
There are times when a user wants to customize what an operator will watch. Right now, watches.yaml is fixed and cannot be customized or configured. This feature at least allows the operator to be somewhat configurable by passing in env vars in the operator's subscription or directly in its Deployment.
For one such example, I may have an operator that can be deployed on OpenShift and non-OpenShift environments. I therefore could have two different sets of playbooks in my operator container - one for OpenShift and one for …

replace all ${VAR} references with env var values in watches yaml

---

internal/ansible/runner/runner.go

This change adds back the MarkUnsafe fix that got lost when moving repos around.
Fix https://github.com/operator-framework/ansible-operator-plugins/issues/41

Add MarkUnsafe fix back

---

pkg/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
testdata/memcached-molecule-operator/Makefile

Resolves: https://github.com/operator-framework/ansible-operator-plugins/issues/48
Currently, the `make docker-buildx` target does not work for ansible operators as we found out in the github.com/ansible/eda-server-operator.  See details here:
* https://github.com/ansible/eda-server-operator/pull/158
Users want to be able to build ansible operators for platforms other than the one on the build system or local machine.  
cc @everettraven

Remove broken work-around for specifying build platforms for the operator image

---

go.mod
go.sum
hack/generate/samples/ansible/advanced_molecule.go
hack/generate/samples/ansible/memcached.go
hack/tests/e2e-ansible-molecule.sh
images/ansible-operator/Dockerfile
images/ansible-operator/pipfile.Dockerfile
pkg/plugins/ansible/v1/scaffolds/internal/templates/config/rbac/role.go
pkg/plugins/ansible/v1/scaffolds/internal/templates/requirements.go
pkg/plugins/util/cleanup.go
testdata/memcached-molecule-operator/config/default/kustomization.yaml
testdata/memcached-molecule-operator/config/default/manager_auth_proxy_patch.yaml
testdata/memcached-molecule-operator/config/manager/manager.yaml
testdata/memcached-molecule-operator/config/prometheus/monitor.yaml
testdata/memcached-molecule-operator/requirements.yml

Bump Kubebuilder to v3.13.0 and fix up scaffolding to handle the incoming breaking changes.
Operator SDK already bumped its kubebuilder dependency to v3.13.0, but it still uses a version of this package that is on a prior version.
Kubebuilder 3.13.0 seems to have made some changes in its `kustomize` plugin that break the expectations of downstream plugins (like this one)
In order to fix things up, we need to _also_ bump this repo to Kubebuilder v3.13.0, fix up its scaffolding to handle the incoming breaking changes, make a release, and then bump operator-sdk.
This PR is the first step of the process.

bump kubebuilder to v3.13.0 and fixup scaffolding

---

images/ansible-operator/Pipfile
images/ansible-operator/Pipfile.lock

This PR updates a couple of dependencies in the ansible-operator image. This attempts to be an incremental update so that we can resolve other issues related to the image building pipeline.
These packages were directly in scope:
```
urllib3
certifi
setuptools
zipp
cryptography
```
The `pipenv check` call throws a couple of new vulnerabilities that require dependency bumps. Of those, only `urllib3` is captured in the Pipfile, the rest are being pulled in from other dependencies, so we're just updating lock constraints for those. 
**EDIT**
As expected, the 2.x series of urllib breaks ansible_runner_http (see https://github.com/operator-framework/ansible-operator-plugins/issues/86) so, instead I take a page out of another PR's …

Update dependencies to resolve safety-cli alerts

---

hack/generate/samples/ansible/testdata/inventory/hosts
images/ansible-operator/Dockerfile
images/ansible-operator/Pipfile
images/ansible-operator/Pipfile.lock
images/ansible-operator/pipfile.Dockerfile

- Bump the base image used in ansible-operator's container image to use UBI9 (From UBI9)
- Bump the Python version to Python 3.12 (from Python 3.9)
There's an active initiative to bump various software versions for the ansible-operator project to move it inline with the current state of packages that are available. This PR just focuses on bumping the UBI and be based off of RHEL9, and bumps the Python version at the same time to move away from the system's (image's) default.
The goal was to be as close to the original design as possible. Some changes to the underlying design were made with intention to minimize or simplify requirements.
**Notes for reviewers**
- UBI9 comes with python 3.9 by default, available at …

Bump base image to RHEL9 and Python version to 3.12

---

.github/workflows/release.yml
.goreleaser.yml
images/ansible-operator/Dockerfile

- Add a cache-building phase of the release workflow, which uses [Docker's GitHub Actions cache backend](https://docs.docker.com/build/cache/backends/gha/) to cache images
- Modify the goreleaser configuration to leverage said cache when building images
- The Release process has had issues completing from time to time, hitting long timeouts.
- In doing a deep dive, I think the cause is either (a) storage on runners, or (b) CPU utilization. I can't really diagnose either reliably without running a self-hosted runner, and there's no guarantee that I can replicate.
- We've seen build times of anywhere from 35 minutes, to as long as 4 hours (after I extended timeouts).
- The project is committed to Goreleaser as a release …

Utilize GitHub Actions cache for image builds

---

internal/ansible/runner/runner.go

There are two magic variables in ansible-operator, one for the `_spec` and containing the whole object. If we have some jinja syntax in the annotations or in the status, `markUnsafe` currently misses it and it fails when injecting the variable in the playbook/role.

mark unsafe the non-spec obj parameter

---

.github/workflows/release.yml
.github/workflows/test-ansible.yml
.github/workflows/test-sanity.yml
.github/workflows/unit.yml

Update github actions to use node 20
Removing the warnings that are shown when running ci checks

Update github actions to use node 20

---

internal/ansible/controller/status/utils.go
internal/ansible/controller/status/utils_test.go

Its required for status to continue to update its message, despite the playbook remaining in a Failure mode.
Without this, the admin only sees the first error that the playbook met, and never see any new errors than happens has more reconciles continue to fail on distinct steps.

in case of failure, we want to update the error to latest run

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/support-question.md

remove the operator type selections from this repo's issues templates
everything in this repo is for the ansible operator type, so having a selection and the noise from the bot doesn't make sense.

removing operator types from issues

---

images/ansible-operator/pipfile.Dockerfile

In https://github.com/operator-framework/ansible-operator-plugins/pull/126 PR, the vulnerability was fixed. So, there is no need to ignore it anymore.
Stop ignoring already fixed vulnerability.

Remove `--ignore 70612` from  `pipenv check` in pipfile.Dockerfile

---

images/ansible-operator/Pipfile
images/ansible-operator/Pipfile.lock

- Fix CVE-2025-27516 by updating `ansible-core` dependency to `v2.18.3`.
- It also updates `jinja2` to `v3.1.6`.
- Closes: https://github.com/operator-framework/ansible-operator-plugins/issues/138
Fix CVE-2025-27516

Security: Fix CVE-2025-27516 by updating ansible-core to v2.18.3

---

pkg/plugins/ansible/v1/scaffolds/internal/templates/makefile.go
testdata/memcached-molecule-operator/Makefile

This PR adds the --ignore-not-found parameter to the kubectl call when calling `make undeploy` and `make uninstall`.
This avoid failure of any of these two commands if for some reason one or more of the kustomized resource is missing.
Part of https://github.com/operator-framework/operator-sdk/issues/5195

scripts: add ignore-not-found for undeploy and uninstall to Makefile boiler plate
